name: Update Time
on:
  schedule:
    - cron: '0 * * * *'
    - cron: '30 * * * *'
jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run update-status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
